FROM node:15.5-alpine
RUN npm install -g http-server
# make the 'app' folder the current working directory
WORKDIR /app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY ../package.json package.json
COPY ../package-lock.json package-lock.json
RUN npm install
# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY .. .

# build app for production with minification
#RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
