version: "3.9"

services:
  webdev:
    image: node:alpine
    user: node
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: ["/bin/sh", "-c", "node app.js"]
volumes:
  postgres-vol:
